apiVersion: v1
kind: Secret
metadata:
  name: minecraft-bot
  namespace: minecraft-bot
type: Opaque
stringData:
  # Your Discord Bot Token
  TOKEN: "..."
  # Your Discord App ID
  APP_ID: "..."
  # The Discord Server to run on
  GUILD_ID: "..."
  # The Discord Role allowed to approve requests
  MC_APPROVERS: "..."
  # Your Minecraft server RCON info
  MC_RCON_ADDRESS: "minecraft:12345"
  MC_RCON_PASSWORD: "..."
