apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: minecraft-bot
  namespace: minecraft-bot
subjects:
- kind: ServiceAccount
  name: minecraft-bot
  namespace: minecraft-bot
roleRef:
  kind: Role
  name: minecraft-bot
  apiGroup: rbac.authorization.k8s.io